enum ImageGeneration {
  RED_GREEN,
  RED_BLUE,
  YELLOW,
  GOLD,
  SILVER,
  CRYSTAL,
  RUBY_SAPPHIRE,
  EMERALD,
  FIRE_RED_LEAF_GREEN,
  DIAMOND_PEARL,
  PLATINUM,
  HEARTGOLD_SOULSILVER,
  BLACK_WHITE,
  THREE_D_GIF,
  LETS_GO,
  SWORD_SHIELD,
  SCARLET_VIOLET
} export default ImageGeneration;
